version: '3.9'

services:
  postgres:
    container_name: teacher-ai-server
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/libs/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: teacherai
      POSTGRES_PASSWORD: teacherai

volumes:
  postgres_data: